# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and info. See https://dart.dev/tools#ides-and-editors

include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - import_lint

linter:
  rules:
    avoid_relative_lib_imports: true

import_lint:
  severity: error
  rules:
    domain_no_flutter:
      target: "package:ciel_mobile/domain/**/*.dart"
      from: "package:flutter/**"
      except: []
    domain_no_riverpod:
      target: "package:ciel_mobile/domain/**/*.dart"
      from: "package:flutter_riverpod/**"
      except: []
    domain_no_get_it:
      target: "package:ciel_mobile/domain/**/*.dart"
      from: "package:get_it/**"
      except: []
    domain_no_data:
      target: "package:ciel_mobile/domain/**/*.dart"
      from: "package:ciel_mobile/data/**"
      except: []
    domain_no_features:
      target: "package:ciel_mobile/domain/**/*.dart"
      from: "package:ciel_mobile/features/**"
      except: []
    domain_no_app:
      target: "package:ciel_mobile/domain/**/*.dart"
      from: "package:ciel_mobile/app/**"
      except: []
    data_no_features:
      target: "package:ciel_mobile/data/**/*.dart"
      from: "package:ciel_mobile/features/**"
      except: []
